#!/usr/bin/env bash
# Function to display information about a subdomain

display_info() {
    local domain="$1"
    local subdomain="$2"
    
    line=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1)
    echo "$line" | awk -v subdomain="$subdomain" '{print "The subdomain " subdomain " is a " $4 " record and points to " $5}'
}

# Check if only domain parameter is provided
if [ -z "$2" ]; then
    # Default subdomains
    subdomains=("www" "lb-01" "web-01" "web-02")
    
    # Display information for default subdomains
    for subdomain in "${subdomains[@]}"; do
        display_info "$1" "$subdomain"
    done
else
    # Display information for the specified subdomain
    display_info "$1" "$2"
fi

