#!/usr/bin/env bash
# Function to display information about a subdomain

display_info(){
local subdomain=$1
local domain=$2

line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}
}

if ["$1" == 1]
then
display_info "$1" "www"
display_info "$1" "lb-01"
display_info "$1" "web01"
display_info "$1" "web-02"
elif ["$1" == 2]
then
display_info "$1" "$2"
fi
