#!/usr/bin/env bash

# Assign parameters to variables
FILE_PATH = "$1"
SEVER = "$2"
USERNAME"$3"
SSH_KEY = "$4"

if [ $# -lt 3 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
    exit;
fi;

if [ $# -eq 3 ]; then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
else
  scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
