#!/usr/bin/env bash
# Assign parameters to variables
#FILE_PATH = "$1"
#SEVER = "$2"
#USERNAME"$3"
#SSH_KEY = "$4"

if [ $# -lt 4 ]
	then
		echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
        exit 1

	else
		scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi
