#!/usr/bin/env bash
# A Script that configures a new Ubuntu machine to Perform a 301-redirection

sudo apt-get -y update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# configure Nginx for redirection
sudo bash -c 'cat <<EOF | sudo tee /etc/nginx/sites-enabled/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://bentechnews.blogspot.com;
    }
}
EOF'

# Restarting Nginx service
sudo service nginx restart

