#!/usr/bin/env bash
#Install nginx web server

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

NEW_RULE="server_name_;\\n\\trewrite^/redirect_me https://www.benzoic.tech;"

sudo sed -i "s#server_name _;#$NEW_RULE#" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart
