#!/usr/bin/env bash
# A Script that configures a new Ubuntu machine to Perform a 301-redirection

sudo apt-get -y update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Using sed to do a 301 Redirection
NEW_RULE="\\n\\tlocation /redirect_me {\\n\\t\\treturn 301 https://github.com/benzoic09;\\n\\t}\\n"
sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.bakup
sudo sed -i "/server_name _;/a $NEW_RULE" /etc/nginx/sites-enabled/default

# Restarting Nginx service
sudo service nginx restart

