#!/usr/bin/env bash
# A Script that configures a new Ubuntu machine to have a custom 404 page

# Update package lists
sudo apt-get -y update

# Install Nginx
sudo apt-get install -y nginx

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Modify Nginx configuration to use the custom 404 page
sudo bash -c 'cat <<EOF | sudo tee /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://bentechnews.blogspot.com;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}
EOF'

# Restart Nginx service
sudo service nginx restart

