#!/usr/bin/env bash
#Install nginx web server

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.github.com/benzoic09 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sed -i "/redirect_me/ a\\\terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default

sudo service nginx restart
