#!/usr/bin/env bash
# Create a script to configure nginx on a new server

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Retrieve the hostname of the server
SERVER_HOSTNAME=$(hostname)

# Configure Nginx to include custom HTTP response header
echo "add_header X-Served-By $SERVER_HOSTNAME;" | sudo tee -a /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx
