#!/bin/bash

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Enable HAProxy management via init script
sudo sed -i 's/^ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy to send traffic to web-01 and web-02 with roundrobin algorithm
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 437142-web-01 100.24.255.166 check
    server 437142-web-02 34.207.190.235 check
EOF

# Restart HAProxy to apply changes
sudo systemctl restart haproxy
