#!/usr/bin/env bash

# Update package lists
sudo apt-get -y update

# Install HAProxy
sudo apt-get install -y haproxy

# Enable and start HAProxy management via init script
sudo service haproxy start
sudo service haproxy enable

# Configure HAProxy to send traffic to web-01 and web-02 with roundrobin algorithm
echo <<EOF | sudo tee -a /etc/haproxy/haproxy.cfg

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server 437142-web-01 100.24.255.166:80 check
    server 437142-web-02 34.207.190.235:80 check
EOF

# Restart HAProxy to apply changes
sudo service haproxy  restart
