#!/usr/bin/env bash
# Fix nginx to listen to port 80
#sudo sed -i "/^listen 70;/a\    listen 80;" /etc/nginx/sites-available/default
sudo ln  -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
